### ISSUE TITLE
S3.delete can be used on browser...

### ISSUE THREAD

**Issue by lamnguyenhong96** [Lepozepo/S3#100]
Is there any way that I could only use S3.delete method in server.

**Comment by gsabran** [comment]
can it? It will call the method `_s3_delete` https://github.com/Lepozepo/S3/blob/master/client/functions.coffee#L149-L150 that fails if the config is correctly setup https://github.com/Lepozepo/S3/blob/master/server/delete_object.coffee#L10

**Comment by Lepozepo** [comment]
You can use the `_s3_delete` method for sure ^_^

**Comment by gsabran** [comment]
If you want to delete the file from the server and not the client, ie have `S3.config.denyDelete` to true and still be able to delete files from the server, you can simply use `S3.knox.deleteFile path` form the server

**Comment by Lepozepo** [comment]
Oh crap, that `denyDelete` is a bad implementation for security, lol

**Comment by gsabran** [comment]
why is that? you can't change it from the client, can you?

**Comment by Lepozepo** [comment]
You can't but that's not the issue. The problem is that it's just a variable so there's no flexibility for the dev to actually put some logic into it. It's either always true or always false, lol. I just pushed a fix for it though.
