### ISSUE TITLE
Progress Bar

### ISSUE THREAD

**Issue by kalepail** [Lepozepo/S3#11]
Any luck with a progress bar?
I'm looking at using this on a large project but am curious how far you hope to take it.

**Comment by richpowell** [comment]
tagging on here a simple bootstrap styling.. it will show an animated bar.. just in case anyone needs the refresher.
    {{#each files}}
    <div class= "progress progress-striped progress-success">
      <div class="progress-bar" style="width:{{percent_uploaded}}%">
    <span style="padding:2px; float:left; color:#000;">{{percent_uploaded}}%</span>
  </div>
  </div>
    {{/each}}

**Comment by richpowell** [comment]
{{#each files}}
   `<div class= "progress progress-striped progress-success">
      <div class="progress-bar" style="width:{{percent_uploaded}}%">
    <span style="padding:2px; float:left; color:#000;">{{percent_uploaded}}%</span></div></div>`
    {{/each}}

Just in case anyone needed the a quick bootstrap how to on animating a progress bar..
