### ISSUE TITLE
On the apk images are not appearing

### ISSUE THREAD

**Issue by aviavia** [Lepozepo/S3#124]
hi,
I use the module and have no issues.
When I visit the app from a browser, I see all the images as expected. But when opening the apk app at Android device,I don't see any images.
What am I missing?
Thanks.

**Comment by dannyvassallo** [comment]
@aviavia This is just a guess -- Checkout the browser policy package https://atmospherejs.com/meteor/browser-policy and see if changing your browser policy enables the app to access the photos.

**Comment by aviavia** [comment]
checking it...Thanks a LOT!

**Comment by aviavia** [comment]
It didn't help.
BrowserPolicy.content.allowImageOrigin("http://*.com");

**Comment by dannyvassallo** [comment]
Try just the wildcard:

`BrowserPolicy.content.allowImageOrigin("*");`

**Comment by aviavia** [comment]
No change.

**Comment by aviavia** [comment]
Maybe I need to rebuild the apk after these changes?

**Comment by dannyvassallo** [comment]
You would absolutely need to rebuild the apk -- did you try any other images from external sources in your app? Or just the s3 urls?

**Comment by aviavia** [comment]
I have an external video which also not appearing.
I will rebuild the apk and try. I knew i should rebuild if i make changes on the mobile-config file, not at changes at the server.
Thanks.

**Comment by aviavia** [comment]
Thank you very much . with a new build it works...

**Comment by dannyvassallo** [comment]
No problem. @Lepozepo you can close this as it was not an issue with your package.

**Comment by Lepozepo** [comment]
Sweet!
