### ISSUE TITLE
Transfer Acceleration

### ISSUE THREAD

**Issue by harrisonhunter** [Lepozepo/S3#128]
Is there currently a way to enable transfer acceleration for uploads to S3 (http://docs.aws.amazon.com/AmazonS3/latest/dev/transfer-acceleration.html)?
If so can an example be added?
If not, do you have any insight on how and if that could be implemented so that people can take advantage of the new S3 improvements?

**Comment by joaopiopedreira** [comment]
Hi @harrisonhunter , you can enable transfer acceleration on the bucket itself (S3 console, under "transfer acceleration" on the bucket properties). Or do you mean activating transfer acceleration on demand (on/off)? 

Be wary of that though - if your bucket and your clients are in the same AWS region, you can loose speed! Checkout their [speed comparison tool](http://s3-accelerate-speedtest.s3-accelerate.amazonaws.com/en/accelerate-speed-comparsion.html?region=eu-west-1&origBucketName=routesdirect-files).

**Comment by harrisonhunter** [comment]
I realize my post above was unclear. I was looking to use transfer acceleration with this package (following instructions here: http://docs.aws.amazon.com/AmazonS3/latest/dev/transfer-acceleration.html). I have transfer acceleration enabled on my bucket (step 1) but was looking for any guidance on how to transfer to the accelerated end point (step 2).

**Comment by joaopiopedreira** [comment]
Sorry, didn't quite get your point.

If you mean the below, I'm sure that this package doesn't do it.

>Transfer data to the acceleration-enabled bucket using the bucketname.s3-accelerate.amazonaws.com endpoint – When uploading to or downloading from the Transfer Acceleration enabled bucket you must use the bucket endpoint domain name bucketname.s3-accelerate.amazonaws.com to get accelerated data transfers. You can find the unique Transfer Acceleration endpoint name for your bucket in the Amazon S3 management console.
Note
>You can continue to use the regular endpoint in addition to the accelerate endpoint.
For example, let's say you currently have a REST API application using PUT Object that uses the host name mybucket.s3.amazonaws.com in the PUT request. To accelerate the PUT you simply change the host name in your request to mybucket.s3-accelerate.amazonaws.com. To go back to using the standard upload speed, simply change the name back to mybucket.s3.amazonaws.com.
 
>You can use the new accelerate endpoint in the AWS CLI, AWS SDKs, and other tools that transfer data to and from Amazon S3. If you are using the AWS SDKs, some of the supported languages use an accelerate endpoint client configuration flag so you don't need to explicitly set the endpoint for Transfer Acceleration to bucketname.s3-accelerate.amazonaws.com. For examples of how to use an accelerate endpoint client configuration flag, see Amazon S3 Transfer Acceleration Examples."

It's quite easy to achieve, however, if you tweak the meteor method _s3_sign (and S3.upload). You should define a new parameter (say, "acceleration") and do something like below:

```
		# Identify post_url
		if ops.acceleration
				post_url = "https://#{ops.bucket}.s3-accelerate.amazonaws.com"
		else
			if ops.region is "us-east-1" or ops.region is "us-standard"
				post_url = "https://s3.amazonaws.com/#{ops.bucket}"
			else
				post_url = "https://s3-#{ops.region}.amazonaws.com/#{ops.bucket}"

```

I'll try it this week and will let you know.

**Comment by harrisonhunter** [comment]
Yes that is what I meant. Let me know if you have any success with that approach I will also try soon and give an update if I get it to work. Thanks!
