### ISSUE TITLE
Adding pre-signed URL support

### ISSUE THREAD

**Issue by macsj200** [Lepozepo/S3#137]
Hello, I'd like to start off by thanking the maintainers for their hard work on this package. It's a very solid piece of software that has saved me a lot of time 😃.

Would it be possible to add [pre-signed URL](http://docs.aws.amazon.com/cli/latest/reference/s3/presign.html) support? I would like to restrict viewing of files, and [the SO question I asked](http://stackoverflow.com/questions/41918449/how-to-set-visibility-read-permissions-on-s3-uploads/41918888#41918888) about doing this kind of thing pointed to pre-signed URLs as the way to go.

I saw PR #95  for what I think is support for this functionality. Can someone help me review the code , and possibly merge it?

ping @wesleyfsmith

**Comment by Lepozepo** [comment]
Ah! I wasn't aware of that @macsj200. Have a look at the new version of S3 that I built. I'm trying to make it more flexible [here](https://www.npmjs.com/package/s3up) this will be the version that is going to replace this one. Notice the `Authorizer` creates an instance of AWS S3 under the hood, but you could tap into this from the `Authorizer` now via `Authorizer.S3.getSignedUrl`. Let me know what you think. I could expose all of the S3 methods though as well for ultimate flexibility.

**Comment by macsj200** [comment]
Ok, I'll open an issue on the new repo.
