### ISSUE TITLE
Name of the file automatically changes in s3 when i upload 

### ISSUE THREAD

**Issue by vyas07** [Lepozepo/S3#139]
Name of the file automatically changing in s3 when i upload
**example :** file name in local = mypic.jpg
In s3 bucket it is showing  3a139e01-b2f9-4300-92f7-0e13956775c8.jpg
I dont want it to be encrypted ,i want my file name to be same as local in s3

**Comment by Lepozepo** [comment]
Set the `unique_name` flag to false or set `upload_name` on your file object

**Comment by vyas07** [comment]
thankyou :)
