### ISSUE TITLE
Add support for GovCloud region

### ISSUE THREAD

**Issue by wcgcoder** [Lepozepo/S3#163]
Hello,

Respectfully request that us-gov-west-1 be added to the allowable regions with its corresponding endpoint: s3-us-gov-west-1.amazonaws.com

Thank you!

**Comment by Lepozepo** [comment]
@wcgcoder I believe that should work considering how https://github.com/Lepozepo/S3/blob/master/server/sign_request.coffee#L74 this line works. Are you seeing any logs or errors coming back from S3?

**Comment by wcgcoder** [comment]
@Lepozepo thanks for looking into it. The code you've referenced should yield the correct output; I was getting an invalid string match error before, but I can't reproduce the problem today... 
I'll let you know if I can reproduce the problem in the future. Thanks!

Edit: apologies. I think the problem I'm encountering is coming from the validation in another library outside of yours! Thanks for your attention. Please close this issue.

**Comment by Lepozepo** [comment]
Sweet ^_^
