### ISSUE TITLE
Exception in _S3upload. No method  'putStream'

### ISSUE THREAD

**Issue by jakoblind** [Lepozepo/S3#51]
Hi,

I'm having an issue with the S3.upload method call. I use Meteor 1.0 and S3 4.1.3. I get the following exception.

I20141202-14:08:24.107(1)? Exception while invoking method '_S3upload' TypeError: Object #<Object> has no method 'putStream'
I20141202-14:08:24.108(1)?     at Meteor.methods._S3upload (packages/lepozepo:s3/server/methods.coffee:40:19)
I20141202-14:08:24.108(1)?     at maybeAuditArgumentChecks (packages/ddp/livedata_server.js:1599)
I20141202-14:08:24.108(1)?     at packages/ddp/livedata_server.js:648
I20141202-14:08:24.108(1)?     at _.extend.withValue (packages/meteor/dynamics_nodejs.js:56)
I20141202-14:08:24.109(1)?     at packages/ddp/livedata_server.js:647
I20141202-14:08:24.110(1)?     at _.extend.withValue (packages/meteor/dynamics_nodejs.js:56)
I20141202-14:08:24.110(1)?     at _.extend.protocol_handlers.method (packages/ddp/livedata_server.js:646)
I20141202-14:08:24.110(1)?     at packages/ddp/livedata_server.js:546

**Comment by enaros** [comment]
hey, any updates on this? I am experiencing the same issue :) any help appreciated!

**Comment by Lepozepo** [comment]
Hey guys, I haven't had the opportunity to have a look at what might be causing this. Hope to update this package as soon as I finish my current project.

**Comment by enaros** [comment]
hey @Lepozepo, finally it was't the same problem than the other guy, I just had audit-permit-check on and your server-side methods don't check any parameters, hence it was failing

**Comment by Lepozepo** [comment]
Hey guys! The new uploader does not use streams anymore so this should not be an issue. I'll patch the new release to run checks on the methods I'm using so that it doesn't have issues with audit-permit-check ^_^. Thanks @enaros!
