### ISSUE TITLE
_S3_multipart_upload result in corrupt files

### ISSUE THREAD

**Issue by henrikgs** [Lepozepo/S3#52]
Files that exceeds the chunk_size threshold of 5.3MB ([streams.coffee](https://github.com/Lepozepo/S3/blob/master/shared/streams.coffee#L10)), and [therefore](https://github.com/Lepozepo/S3/blob/master/client/functions.coffee#L65-89) uses the [_S3_multipart_upload](https://github.com/Lepozepo/S3/blob/master/server/methods.coffee#L107-201) method for uploading to S3, always result in corrupt files (as far as I've seen). It seems that the file sizes decrease after being uploaded to S3 with _S3_multipart_upload, which may be related to the data corruption.

**Comment by Lepozepo** [comment]
I have completely reprogrammed the uploader, this should not happen anymore. Uploads now occur directly from client to S3 and never touch your server.
