### ISSUE TITLE
Stopping upload of file over a certain size?

### ISSUE THREAD

**Issue by sgoudie** [Lepozepo/S3#54]
I tried returning r.total_uploaded to check file size, but it came back undefined. I really need to check the file size and stop the upload before it starts, but could  stop the upload when it reaches a certain amount.

Any ideas?

**Comment by Lepozepo** [comment]
If you are trying to prevent a particular file size from uploading, you can target the file directly and just check the size property on it (if the browser was capable of identifying the size of the file). Is that what you were trying to do?
