### ISSUE TITLE
Allow direct filename editing and/or maintain original filename

### ISSUE THREAD

**Issue by Raynes** [Lepozepo/S3#59]
In my particular use case this (and every other) library complicates things by enforcing a file rename. I have to rename my file to its original name in an incredibly hacky way. I'd love an option to just allow overwriting files.

**Comment by chrissuperduper** [comment]
+1

**Comment by Lepozepo** [comment]
Hi guys, I have completely upgraded the uploader. The random file size failures should be gone now. Do you still need a way to overwrite file names? Or is it good enough with having the original file name persist?

**Comment by Raynes** [comment]
Having the original filename persist is great! Awesome stuff.

**Comment by cranesandcaff** [comment]
Did you end up adding this?
