### ISSUE TITLE
Add a way to identify 2 or more separate uploaders in the same template

### ISSUE THREAD

**Issue by sivailango** [Lepozepo/S3#60]
Hi,
I have two file upload section with respective upload button on same template. Both files will be uploaded seperate folder in S3 bucket. For example file 1 should be uploaded to 'mybucket/folder1', second should be 'mybucket/folder2'. I dont know how to show progress for both section separately. 

Template.addClient.helpers({
	sopFiles : function(){
        return S3.collection.find();
    },
	templateFiles : function(){
        return S3.collection.find();
    }
});

I know both helpers returns same progress bar. 

Can we restrict in S3.collection.find() using current upload progress?

**Comment by tom2strobl** [comment]
I assume one could just create a tiny subtemplate to counter this issue, right?

**Comment by sivailango** [comment]
Hi tom,

can you post sample piece of code?

**Comment by Lepozepo** [comment]
Hey guys! S3.upload now accepts an uploader parameter (look at docs) to be able to distinguish from multiple uploaders on the same page. The S3.collection collection now has a respective uploader key for each upload made as well.
