### ISSUE TITLE
Using the package with different regions / problem uploading

### ISSUE THREAD

**Issue by vazamb** [Lepozepo/S3#62]
Hey!

I tried using the package but am having difficulty uploading anything. I get no error when invoking S3.upload and it happily returns an URL. However, the file does not get uploaded. It doesn't show up in the S3 console on AWS and the link that the function returns throws a 404 error when used. 
I realised that the links generated by Meteor/the package were different than if I upload something by hand. For example:
This file actually exists and is viewable:
https://s3.eu-central-1.amazonaws.com/taskwunder-appt/handshake.png

This URL was generated by Meteor and is not useable:
http://taskwunder-appt.s3.amazonaws.com/avatar/t4q5gth8XX4y8XbqH.png

I have added this to the S3.config.
region: 'eu-central-1'

The URL changes but is still not useable:
http://taskwunder-appt.s3-eu-central-1.amazonaws.com/avatar/83S4aPeGtsTcHJKDD.png

Is the package not useable with eu-central buckets? Or can I specify the region somewhere else?
EDIT: I created an US Standard bucket and everything seems to work. The issue is definitely with the generation of the URLS when using an EU bucket.

**Comment by Lepozepo** [comment]
Yeah, the package doesn't have region support, I think someone has forked and patched it in. I've been wanting to rework this package for a while now, this is definitely on the to-do list. I do however recommend using the slingshot package instead of this one for now.

**Comment by Lepozepo** [comment]
Hey, this issue should now be supported under the new commit f8875a35888f4d56071e0d93ea1c87282d5ad7f2
