### ISSUE TITLE
Not working under ios (cordova)

### ISSUE THREAD

**Issue by geritol** [Lepozepo/S3#63]
Somehow not working on ios device (using cordova running locally).

**Comment by idmontie** [comment]
Which part isn't working?  Can you give a repo that reproduces the problem?

**Comment by geritol** [comment]
Don't know exactly... It works pefektly on desktop, but somehow S3.upload wont do anything with cordova. Here is a repo reproducing the problem. Note, that i have made a little bit of change on the pakcage (see here https://github.com/geritol/S3/commit/f78a13241e64555043325fc78442ad7421b43845) to be able to upload blob or base64 files.

https://github.com/geritol/cordova-s3

**Comment by Lenin7** [comment]
Same problem here. It won't upload anything on cordova

**Comment by geritol** [comment]
The problem is that this plugin curently only uploads Files, and the camera plugin outputs base64. You can solve the problem by creating file object from your base64, but this only works on standard clients (not in cordova). This is a very requested feature (see https://github.com/Lepozepo/S3/issues/35), and @kevohagan managed to make it work https://github.com/Lepozepo/S3/pull/36 (not working for me). @Lepozepo says he will update the package soon. So it seems an update to this is coming.

**Comment by Lepozepo** [comment]
@geritol I think you'll be moderately happy with this update: c7fa79e7124e6d0414f91d95fc3c883a15f15c62

It was a fairly easy implementation. Now it needs a library to parse base64 extensions like a pro.

**Comment by geritol** [comment]
Thanks for that!
I am trying to send a base64 string starting with ""data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDA", and i get InvalidCharacterError: String contains an invalid character (s3.js 158:0). (I am using lepozepo:s3 v. 5.1.0)

**Comment by Lepozepo** [comment]
Are you sure that's a valid string? I pasted it to an img tag and got nothing.

**Comment by geritol** [comment]
Im am pretty sure (what i pasted here is only the starting of it cause it is pretty long.)

**Comment by jstoup111** [comment]
Is this something that's going to get fixed? I get the same error.

**Comment by Lepozepo** [comment]
I think I had a look at it but didn't have the time to finish it up. I'll have a second look as soon as I can.
