### ISSUE TITLE
How can I invoke S3 delete method on server side?

### ISSUE THREAD

**Issue by sparupat** [Lepozepo/S3#67]
Hi, 

I am trying to delete a uploaded file on S3 bucket from server side instead of client. I tried to use '_s3_delete' method, but it did not work. Can you please tell me the right way to invoke delete functionality on server side?

Thanks you,
Sri

**Comment by Lepozepo** [comment]
Can you link a code of what you tried on the server? And are you by any chance using any particular regions?

**Comment by sparupat** [comment]
Thanks you so much for the response. 

I have a use case where user uploads an image to server. Server runs image processing algorithm on image and deletes it from S3 based on algorithm results.

I tried to invoke delete method using below command

>>> _s3_delete('relativeImageURL');

I uploaded image to S3 using Slingshot library with 'us-west-2' region setting.

**Comment by Lepozepo** [comment]
That function does not exist, lol. Take a look at this example:

https://github.com/Lepozepo/S3/blob/master/example/basic/basic.coffee

The function you want to use is S3.delete()
