### ISSUE TITLE
Error: No 'Access-Control-Allow-Origin' header.

### ISSUE THREAD

**Issue by pwever** [Lepozepo/S3#72]
I get the following error, when uploading to S3 (using the latest meteor release):

> XMLHttpRequest cannot load https://s3.amazonaws.com/groceriesimagery. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access.

My feeling is that the  [bucketname] is not correctly added to the host header in the HTTP OPTIONS request. Please see below steps to replicate:

## How to replicate

- [x] Clone/download the [S3 project!](https://github.com/Lepozepo/S3)
- [x] Add you S3 bucket key, secret and name.
- [x] Run and test the upload to S3 storage.
- [x] Run "meteor update" to move to the latest release.
- [ ] Run and test the upload again. *(all good up until this step)*

## HTTP headers using the original example (successful):

```
POST / HTTP/1.1
Host: [bucketname].s3.amazonaws.com:443
Accept: */*
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.8,de;q=0.6
Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryoTY94bqHHum3LBBI
Origin: http://localhost:3000
Referer: http://localhost:3000/
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.90 Safari/537.36
X-DevTools-Emulate-Network-Conditions-Client-Id: FFA77629-4192-4341-8D7E-E3F9C45094E0

HTTP/1.1 204 No Content
Access-Control-Allow-Methods: PUT, POST, GET, HEAD
Access-Control-Allow-Origin: *
Access-Control-Max-Age: 3000
Date: Thu, 23 Apr 2015 17:16:43 GMT
ETag: "52ae28b9cadca67fcd7e77421c5dcf22"
Location: https://[bucketname].s3.amazonaws.com/tester%2F59af8b7e-e1c3-4f48-96ab-af1a01b64e2b.JPG
Server: AmazonS3
Vary: Origin, Access-Control-Request-Headers, Access-Control-Request-Method
```

## HTTP headers after updating meteor (fails):

```
OPTIONS /[bucketname] HTTP/1.1
Host: s3.amazonaws.com:443
Accept: */*
Accept-Encoding: gzip, deflate, sdch
Accept-Language: en-US,en;q=0.8,de;q=0.6
Access-Control-Request-Headers: content-type
Access-Control-Request-Method: POST
Origin: http://localhost:3000
Referer: http://localhost:3000/
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.90 Safari/537.36
X-DevTools-Emulate-Network-Conditions-Client-Id: FFA77629-4192-4341-8D7E-E3F9C45094E0

HTTP/1.1 301 Moved Permanently
Content-Type: application/xml
Date: Thu, 23 Apr 2015 17:31:48 GMT
Server: AmazonS3
Transfer-Encoding: chunked
```

**Comment by jamgold** [comment]
I had the same issue. Simply running with ROOT_URL=http://myhostname.example.com:3000 solved it

**Comment by pwever** [comment]
Thanks for getting back so quickly. Unfortunately this didn't fix the error for me though. Just to make sure I didn't misunderstand, here is what I tried:

Locally in the basic example directory:
`$ ROOT_URL="http://localhost:3000/" meteor`

I also tried on the staging server, via mup, with the ROOT_URL env set.
`"env": { "ROOT_URL": "http://[amazon-ec2-instance]" }`

Did I misunderstand anything?
Thx // p

**Comment by jamgold** [comment]
I use my externally accessible (NOT localhost) FQDN in ROOT_URL. 

What browser are you using?

**Comment by pwever** [comment]
I am on OSX, so testing primarily with Chrome and Safari and tried both locally using localhost, and remotely, using an EC2 instance, to no avail.

More confusing, I never get the basic example working again, after doing the update once:

1. Download and test the basic example (success)
2. Run `meteor update` and test again (fails)
3. Specify release with `meteor --release 1.0.3.2` and test (fails)
4. Also reverting s3 package back with `meteor add lepozepo:s3@5.0.1` and test (fails)

Any other ideas and pointers are much appreciated.
Thx // p

**Comment by jamgold** [comment]
Can you check https://github.com/jamgold/s3 and see if you can get that to work with your AWS settings? I just tried and everything works just fine, even when running as localhost. And check if the permissions and CORS settings of your bucket are correct.

**Comment by trymbill** [comment]
I'm getting the same error.

**Comment by xi3** [comment]
In my situation, it is because wrong region config, add ```S3.config.region = 'ap-northeast-1';``` for example fixit. The region code can be find in http://docs.aws.amazon.com/general/latest/gr/rande.html#s3_region

**Comment by ashishgupta2** [comment]
I saw the same issue, adding region to config file resolved the issue. Below is the sample server file. Thanks.

S3.config = {
    key: 'AWS Key',
    secret: 'AWS Secret',
    bucket: 'Bucket Name',
    region:"ap-southeast-1"
};

**Comment by chmac** [comment]
We had the same problem, didn't set a region, and didn't pay enough attention to the docs. The region defaults to `us-east-1`, which means we were looking for a bucket that didn't exist in that region.

**Comment by nilsi** [comment]
For me, I got this when I didn't set up the bucket policies like described in the docs.

**Comment by KristerV** [comment]
ah shit, spent a whole day on this all I needed was the region.. updating readme
