### ISSUE TITLE
Is it possible to store files on S3 and get back private, non-public urls?

### ISSUE THREAD

**Issue by niranjans** [Lepozepo/S3#82]
With the CORS config and bucket policy example shown in the Readme and by enabling Static website hosting, I can get the file uploaded perfectly but the url that is returned is publicly accessible.  

Does this package not work if the settings are changed to privately storing files? I'm new to S3 and so I'm not sure what the changes would be and if this package would work.

**Comment by Lepozepo** [comment]
Hi! It shouldn't be a problem. I do however recommend you instead set the configuration to only allow GET from your site instead. I haven't tried that yet so I'm not exactly sure what the configuration is but it shouldn't be too complicated (although digging through Amazon's documentation is a pain in the ass).

**Comment by niranjans** [comment]
Hah, you're right. Their docs are excruciating.
Anyway, thanks for the reply. Makes me confident I'm not digging in to a dead-end.

And thanks for this great package.
