### ISSUE TITLE
No 'Access-Control-Allow-Origin"

### ISSUE THREAD

**Issue by baambooli** [Lepozepo/S3#84]
Hi again,
I get this error on the browser console.

XMLHttpRequest cannot load https://s3-us-west-1.amazonaws.com/mybucket-dc-ab. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3050' is therefore not allowed access.

As the manual said I put s3.upload() on the client side, so why is says it says "No 'Access-Control-Allow-Origin"?

this is event handler (test1.js on the client folder)

   Template.test1.events({
         "click button.upload": function () {
             Meteor.call('configAWSS3');

           var files = $("input.file_bag")[0].files;

           console.log(files);
           S3.upload({
                files: files,
                path: "subfolder"
            },
            function (e, r) {
                if (e) {
                    alert('error: ' + e);
                }
                else {
                    console.log(r);
                    alert('success');
                }
            });
    }

})

and my CORS config on s3 bucket is exactly as manual says.

Thanks

**Comment by baambooli** [comment]
I found the solution, so i leave it here for pother people:
my s3 is on us-west1, but when I put it=> region: "us-west-1"  it does not work and gives the above error. I changed it to "us-east-1"  and it works! I really do not know why but now it works!

**Comment by Lepozepo** [comment]
Lol, that's great to hear. Amazon's docs are cryptic as hell >_<.
