### ISSUE TITLE
HTML not being reset after upload (suggestion)

### ISSUE THREAD

**Issue by petr24** [Lepozepo/S3#85]
I was working with this package and noticed that after a successful upload, the progress bar stays there even if I leave the page and come back. To clear the bar you need a page refresh. I don't know if this is the best way to do this, but for a quick fix I use the template rendered block to clear it. I went through the package briefly and didn't know where you could add this to clear it up at the package level. Thought I'd throw it out there. 

```javascript
Template.editModal.rendered = function () {
	$('.progress').remove();
}
```

**Comment by Lepozepo** [comment]
Remember we are using a client side collection to control our data. If you do not want your loader to show all you need to do is remove the data from the collection OR build a helper that checks whether the collection has been fully uploaded or not. I think the response object has this. Either way, inspect `S3.collection` and you'll figure it out quickly I'm sure.
