### ISSUE TITLE
Individual progress bars when multiple uploader on same form/template

### ISSUE THREAD

**Issue by elzii** [Lepozepo/S3#86]
As far as I understand, there is not a good way to do this because `S3.collection.find()` will populate when one file is uploaded, cause the helper to fire across multiple templates.

Ideas / suggestions?

**Comment by Lepozepo** [comment]
You could build a helper that finds all the files in the collection then sums the size of all the files to get the denominator, then you can do the same for each files' progress and use that for the numerator. Does that make sense?

**Comment by richpowell** [comment]
I'm gonna tag on this bootstrap styling on here.. to actually animate a bar...  just in case anyone needs it.

    {{#each files}}
    <div class= "progress progress-striped progress-success">
      <div class="progress-bar" style="width:{{percent_uploaded}}%">
    <span style="padding:2px; float:left; color:#000;">{{percent_uploaded}}%</span>
  </div>
  </div>
    {{/each}}
