### ISSUE TITLE
No Connection

### ISSUE THREAD

**Issue by privatecaptain** [Lepozepo/S3#88]
Hey, i'm trying to do everything exactly as explained in the README but i'm not able to get a Connection with S3(or thats what i think), i tried checking the connection through  <code> S3.collection._connection</code> but it returned<code> null </code>  and the console doesn't seem to be logging in the <code> callback </code>  function either.

Help me, Thank You

**Comment by Lepozepo** [comment]
The S3 collection is a client side collection only. The package expects you to build your own collection.
