### ISSUE TITLE
Clear S3.collection after a few seconds

### ISSUE THREAD

**Issue by pggalaviz** [Lepozepo/S3#94]
How can I clear the S3.collection so that my progress bar disappear after a few seconds?
I tried this but then when trying to upload another file I had problems.

``` javascript
Meteor.setTimeout(function(){
    S3.collection = null;
}, 5000);
```

**Comment by nicooprat** [comment]
You better use the upload callback, something like:

```js
S3.upload({
  files: files
}, (err, res) => {
  if(err) {
    ...
  } else {
    ...
  }
});
`````

If you want to empty the collection, you should do it like this: `S3.collection.remove({})`

**Comment by Lepozepo** [comment]
```
S3.upload(props, () => setTimeout(() => S3.collection.remove({}), 5000))
```

Something like that would make sense as @nicooprat has stated ^_^
